### ISSUE TITLE
Ability to forch refersh .

### ISSUE THREAD

**Issue by P0bo** [SkyD666/PodAura#80]
Some feed not updating even tho it updates in other rss feed app

link - https://raw.githubusercontent.com/P0bo/Anime-Tosho/main/rssfeed/airing.xml
only if i remove and then add , the new items appear.
The current logic is that the articles in the xml file are sorted in chronological order by default, so when reading the first item, anivu thinks that the following items are older, so it skips them directly.
some feeds have no sorting . and some sort by anime episode number per hour as opposed to sorted by newest . so the order becomes messy in them '
you can try forced refresh , as a different option . in feedflow for these type of feed the refresh option is different , they have two refersh one just refresh and one forced refresh

![Screenshot_2024-08-01-21-13-11-36_ec2eb6fa460e4a1f71f8b51a239fd3fc](https://github.com/user-attachments/assets/d7610336-8d13-468c-b988-d18ff39d3f7d)

 if we can set it per feed when adding the feed or later that would be great since it sorts even the feeds that dot need it  . in this way when mass updating the refresh time will not be that high if some feeds are unsorted type and some aore sorted type by default

**Comment by P0bo** [comment]
```kt
VersionCode: 19
Brand: OnePlus
Model: OPD2203
SDK Version: 34
ABI: arm64-v8a

Crash Info: 
java.lang.IllegalStateException: Expected BringIntoViewRequester to not be used before parents are placed.
 at B.p.a(SourceFile:702)
 at E.j.k0(SourceFile:13)
 at E.g.w(SourceFile:64)
 at Q6.a.l(SourceFile:9)
 at i7.G.run(SourceFile:95)
 at O0.Y.h0(SourceFile:24)
 at O0.X.run(SourceFile:3)
 at android.os.Handler.handleCallback(Handler.java:958)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:257)
 at android.os.Looper.loop(Looper.java:368)
 at android.app.ActivityThread.main(ActivityThread.java:8839)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
 Suppressed: n7.g: [O0.C0@b4a8b17, c0.h@fe86b04, u0{Cancelling}@fa8f8ed, Y@b186322]
```

the crash when i tested the feature by refreshing a group.

**Comment by SkyD666** [comment]
> ```kotlin
> VersionCode: 19
> Brand: OnePlus
> Model: OPD2203
> SDK Version: 34
> ABI: arm64-v8a
> 
> Crash Info: 
> java.lang.IllegalStateException: Expected BringIntoViewRequester to not be used before parents are placed.
>  at B.p.a(SourceFile:702)
>  at E.j.k0(SourceFile:13)
>  at E.g.w(SourceFile:64)
>  at Q6.a.l(SourceFile:9)
>  at i7.G.run(SourceFile:95)
>  at O0.Y.h0(SourceFile:24)
>  at O0.X.run(SourceFile:3)
>  at android.os.Handler.handleCallback(Handler.java:958)
>  at android.os.Handler.dispatchMessage(Handler.java:99)
>  at android.os.Looper.loopOnce(Looper.java:257)
>  at android.os.Looper.loop(Looper.java:368)
>  at android.app.ActivityThread.main(ActivityThread.java:8839)
>  at java.lang.reflect.Method.invoke(Native Method)
>  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:572)
>  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1049)
>  Suppressed: n7.g: [O0.C0@b4a8b17, c0.h@fe86b04, u0{Cancelling}@fa8f8ed, Y@b186322]
> ```
> 
> the crash when i tested the feature by refreshing a group.

https://t.me/SkyD666Chat/6429
